/**
 * Packaging single-source pin: `files` must cover what the build emits, and
 * `src/` is the single source of truth.
 *
 * Layout (see docs/ARCHITECTURE.md): `src/host/*.ts` + `src/client/*.ts` are
 * the sources; `lib/` (single host bundle) and the root `client.js` artifact
 * are GENERATED by `npm run build` and git-ignored. The offline suites import
 * the SOURCES directly, so a clean checkout has no `lib/` and no `client.js`
 * until `npm run build` runs — exactly like the workbuddy upstream.
 *
 * This walks the static relative import graph from the published entry points
 * and fails when a reachable SOURCE is not covered by `files`, plus the build
 * OUTPUT pins (artifact freshness is owned by `build-gate.mjs`). No peer
 * package, no pack step — plain text reads, so it runs on a clean checkout
 * like `config.test.mjs`. Where a check needs the built artifact and none
 * exists (a checkout without `npm run build`), it prints a loud SKIP instead
 * of failing — the same shape as `build-gate.mjs`, so a machine that has not
 * built is never a regression.
 *
 * It also pins the TEST-GATE roster three ways — the suites on disk, the
 * `npm test` chain, and the CI offline job. The trigger was real:
 * `retry.test.mjs` and `draw.test.mjs` (89 peer-free checks over the 429
 * self-heal and the draw absorption) passed standalone for a whole release
 * while no gate ran them. A suite that exists but runs nowhere is the same
 * drift class as a module that ships but is missing from `files` — so it
 * earns the same nail.
 */
import { readFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const manifest = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

const results = [];
function check(name, condition, detail = "") {
  results.push({ name, pass: Boolean(condition), detail });
}

/** The published whitelist, as bare paths. */
const shipped = new Set((manifest.files ?? []).map((entry) => entry.replace(/^\.\//, "")));
const hasLib = shipped.has("lib");

// --- 1. every declared entry point resolves to a built artifact listed in files
// `package.json` is excluded: npm ships it into every tarball unconditionally.
const entries = [...new Set([
  manifest.main,
  ...Object.values(manifest.exports ?? {}).filter((value) => typeof value === "string")
].map((entry) => entry.replace(/^\.\//, "")))].filter((entry) => entry !== "package.json");
for (const entry of entries) {
  // An entry like `lib/index.js` is covered by a directory whitelist entry
  // (`lib`) — the build fills that directory. Accept either exact match or an
  // ancestor directory present in `files`.
  const covered = shipped.has(entry) || entry.split("/").some((_, i, parts) => shipped.has(parts.slice(0, i + 1).join("/")));
  check(`entry ${entry} is in files`, covered, covered ? "" : "entry missing from files");
}

/**
 * Static relative imports of one module: `from "./x.ts"`, `import "./x.ts"`,
 * `import("./x.ts")`, and factory-form `require("./x.ts")`. Bare specifiers
 * (react, peer packages) and `node:` builtins are ignored: those are the
 * runtime's / packer's problem, not the tarball's.
 * @param {string} source - the module's text.
 * @returns {string[]} the imported paths, without the `./` prefix.
 */
function staticImports(source) {
  const found = [];
  const pattern = /(?:from\s*|import\s*\(?\s*|require\s*\(\s*)["'](\.\/[^"']+)["']/g;
  for (const match of source.matchAll(pattern)) {
    found.push(match[1].replace(/^\.\//, ""));
  }
  return found;
}

// --- 2. every SOURCE module reachable from the entry source is under src/host
// The single publishable host bundle is `lib/index.js`, built from
// `src/host/index.ts`. Walking the source graph proves the bundle is a closed
// set over the project's own files (no stray absolute, no leaked peer).
const SRC_ENTRY = join(root, "src", "host", "index.ts");
const seen = new Set();
const queue = [SRC_ENTRY];
while (queue.length > 0) {
  const file = queue.shift();
  if (seen.has(file)) continue;
  seen.add(file);
  const source = readFileSync(file, "utf8");
  for (const dep of staticImports(source)) {
    const abs = join(dirname(file), dep);
    if (!seen.has(abs)) queue.push(abs);
  }
}
check("the host source graph is walkable", seen.size > 0, `${seen.size} module(s) reached`);
// Every reachable source must live under src/host (the build's input root),
// with ONE declared exception: `src/shared/`. That directory is the wire
// contract both halves read (`src/shared/wire.ts`) — TYPE-ONLY exports, erased
// by tsdown at build time, so they add no runtime code to either bundle. Keep
// it that way: a runtime export there would be the first host logic to enter
// the browser artifact, and it would loosen the isolation that
// `docs/ARCHITECTURE.md` §5 assumes.
const SHARED_ROOT = join(root, "src", "shared");
let outside = 0;
for (const file of seen) {
  const inHost = file.startsWith(join(root, "src", "host"));
  const inShared = file.startsWith(SHARED_ROOT);
  if (!inHost && !inShared) outside += 1;
}
check("every host source reachable from the entry lives under src/host (shared type root excepted)",
  outside === 0, outside === 0 ? "" : `${outside} source(s) escaped src/host`);
// The full graph is published as the `lib` directory (one bundle), so the
// whitelist must contain it.
check("files whitelists the built lib/ output", hasLib, hasLib ? "" : "lib missing from files — the host bundle would ship nothing");

// --- 3. every non-directory shipped entry exists (BUILD OUTPUTS SKIP) -------
// `lib` is a directory produced by `npm run build`; `client.js` is the client
// artifact. On a clean checkout without a build they are absent — that is not
// a regression, it is the workbuddy layout, so those two SKIP loudly instead of
// failing. Every other shipped entry (cordis.patch.yml, docs, README...) must
// exist on disk.
for (const entry of shipped) {
  if (entry === "lib" || entry === "client.js") continue;
  if (!entry.endsWith(".js") && !entry.includes(".")) continue; // skip dir-like
  let present = true;
  try { readFileSync(join(root, entry)); } catch { present = false; }
  check(`shipped ${entry} exists`, present, present ? "" : "listed but absent on disk");
}
if (!existsSync(join(root, "client.js"))) {
  console.log("[package.test] SKIP — client.js artifact absent; run `npm run build` to emit it.");
}
if (!existsSync(join(root, "lib", "index.js"))) {
  console.log("[package.test] SKIP — lib/index.js absent; run `npm run build` to emit it.");
}

// --- 4. no hand-written .js source lives at the package root ----------------
// Root must hold only config/docs/asset files; all .js/.ts source lives under
// src/. A stray root .js would be dead weight (or a forgotten artifact).
const rootJs = readdirSync(root).filter((name) => name.endsWith(".js"));
// client.js is the only legitimate root .js and it is a BUILD OUTPUT (git-ignored).
const stray = rootJs.filter((name) => name !== "client.js");
check("no hand-written .js source sits at the package root", stray.length === 0,
  stray.length === 0 ? "" : `stray root .js: ${stray.join(", ")}`);

// --- 5. the browser bundle resolves packages, never paths ------------------
// The Client module table's synchronous `require` (dsh-client-modules,
// `makeRequire`) looks specifiers up by seed word and registered FACTORY ID;
// only `require.async` accepts a `./` path, and only for build-time chunks.
// An unbuilt bundle that requires a relative path therefore loads fine under
// Node in tests — where `import` resolves paths — and throws "missed the
// module table" in the browser: a split that is green everywhere except the
// thing it ships to. This pins the bundle to package specifiers only.
//
// The artifact (client.js) is the authoritative check; when it has not been
// built, fall back to the source (src/client/index.ts), where every relative
// import is bundler-resolved and no runtime `require("./…")` may appear.
{
  const artifact = join(root, "client.js");
  const source = join(root, "src", "client", "index.ts");
  let text = null;
  let label = "";
  if (existsSync(artifact)) { text = readFileSync(artifact, "utf8"); label = "client.js artifact"; }
  else if (existsSync(source)) { text = readFileSync(source, "utf8"); label = "src/client/index.ts source"; }
  if (text === null) {
    console.log("[package.test] SKIP — no client bundle or source to scan for relative requires.");
  } else {
    const scanned = text
      .split("\n")
      .filter((line) => !/^\s*(\/\/|\*)/.test(line))
      .join("\n");
    const relatives = [...scanned.matchAll(/require\s*\(\s*["'](\.\/[^"']+)["']/g)].map((match) => match[1]);
    check(`the client module requires no relative path (${label})`, relatives.length === 0, relatives.join(", "));
    const required = [...new Set([...scanned.matchAll(/require\s*\(\s*["']([^"']+)["']/g)].map((match) => match[1]))];
    check("the client module requires only the platform's package seeds",
      required.every((spec) => spec === "react"), required.join(", "));
  }
}

// --- 6. the test-gate roster is one fact, not three mirrors ----------------
// A suite that exists on disk but is not wired into `npm test` runs for
// nobody; a suite in `npm test` but not in the CI offline job is a local-only
// gate; a CI line naming a removed file rots silently. All three happened or
// were one refactor away. `retry.test.mjs` and `draw.test.mjs` (89 peer-free
// checks over the shipped 429 self-heal and draw-absorption code) sat in the
// first bucket until this pin.
//
// The one deliberate exception is the network tier: `live-jwks.test.mjs` is
// NOT a default-run check (a green offline run must not reach the platform),
// so it is exempted here and pinned EXCLUDED by its own header.
{
  const TEST_DIR = join(root, "test");
  const EXEMPT = new Set(["live-jwks.test.mjs"]);

  const disk = readdirSync(TEST_DIR)
    .filter((name) => name.endsWith(".test.mjs"))
    .filter((name) => !EXEMPT.has(name));

  const listed = (text) => new Set(
    [...text.matchAll(/node test\/([\w.-]+\.test\.mjs)/g)].map((m) => m[1])
  );
  const npmTest = listed(manifest.scripts.test ?? "");
  const ciText = readFileSync(join(root, ".github", "workflows", "ci.yml"), "utf8");
  const ci = listed(ciText);

  // disk ⊆ npmTest and disk ⊆ ci: no orphaned suite.
  for (const name of disk) {
    check(`${name} is wired into the npm test chain`, npmTest.has(name),
      npmTest.has(name) ? "" : "exists on disk but never run by `npm test`");
    check(`${name} is wired into the CI offline job`, ci.has(name),
      ci.has(name) ? "" : "run locally but absent from ci.yml's hard gate");
  }
  // npmTest ⊆ disk and ci ⊆ disk: no ghost reference to a deleted suite.
  const diskSet = new Set(disk);
  for (const name of npmTest) check(`npm test's ${name} exists on disk`, diskSet.has(name),
    diskSet.has(name) ? "" : "chain names a file not in test/");
  for (const name of ci) check(`CI's ${name} exists on disk`, diskSet.has(name),
    diskSet.has(name) ? "" : "ci.yml names a file not in test/");
  // npmTest == ci: the two gates run the same set. e2e-gate is a separate
  // best-effort tier (its own job) and is not a *.test.mjs, so neither side
  // lists it here — the comparison stays exact.
  const onlyNpm = [...npmTest].filter((n) => !ci.has(n));
  const onlyCi = [...ci].filter((n) => !npmTest.has(n));
  check("npm test and the CI offline job cover the same suites",
    onlyNpm.length === 0 && onlyCi.length === 0,
    onlyNpm.length || onlyCi.length ? `only-in-npm=${onlyNpm.join(",")} only-in-CI=${onlyCi.join(",")}` : "");
  // The exempted network suite must STAY out of the default gate — if someone
  // wires it in, the pin fails rather than letting a green run reach the platform.
  check("live-jwks.test.mjs stays out of the default npm test gate", !npmTest.has("live-jwks.test.mjs"),
    "the network tier must not be a default-run check");
}

console.log(JSON.stringify(results, null, 2));
const failed = results.filter((r) => !r.pass);
if (failed.length > 0) {
  console.error(`\n${failed.length}/${results.length} check(s) FAILED`);
  process.exit(1);
}
console.log(`\nall ${results.length} checks passed`);
