/**
 * Packaging single-source pin: `files` must cover what the build emits, and
 * `src/` is the single source of truth.
 *
 * Layout (see docs/ARCHITECTURE.md): `src/host/*.ts` + `src/client/*.ts` are
 * the sources; `lib/` (single host bundle) and the root `client.js` artifact
 * are GENERATED by `npm run build` and git-ignored. The offline suites import
 * the SOURCES directly, so a clean checkout has no `lib/` and no `client.js`
 * until `npm run build` runs — exactly like the workbuddy upstream.
 *
 * This walks the static relative import graph from the published entry points
 * and fails when a reachable SOURCE is not covered by `files`, plus the build
 * OUTPUT pins (artifact freshness is owned by `build-gate.mjs`). No peer
 * package, no pack step — plain text reads, so it runs on a clean checkout
 * like `config.test.mjs`. Where a check needs the built artifact and none
 * exists (a checkout without `npm run build`), it prints a loud SKIP instead
 * of failing — the same shape as `build-gate.mjs`, so a machine that has not
 * built is never a regression.
 *
 * It also pins the TEST-GATE roster: the suites on disk, the `test/suites.mjs`
 * roster, and the CI offline job's invocation of that same roster. The trigger
 * was real: `retry.test.mjs` and `draw.test.mjs` (89 peer-free checks over the
 * 429 self-heal and the draw absorption) passed standalone for a whole release
 * while no gate ran them. A suite that exists but runs nowhere is the same
 * drift class as a module that ships but is missing from `files` — so it
 * earns the same nail.
 */
import { readFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { SUITES, CI_FLAGS } from "./suites.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const manifest = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

const results = [];
function check(name, condition, detail = "") {
  results.push({ name, pass: Boolean(condition), detail });
}

/** The published whitelist, as bare paths. */
const shipped = new Set((manifest.files ?? []).map((entry) => entry.replace(/^\.\//, "")));
const hasLib = shipped.has("lib");

// --- 1. every declared entry point resolves to a built artifact listed in files
// `package.json` is excluded: npm ships it into every tarball unconditionally.
const entries = [...new Set([
  manifest.main,
  ...Object.values(manifest.exports ?? {}).filter((value) => typeof value === "string")
].map((entry) => entry.replace(/^\.\//, "")))].filter((entry) => entry !== "package.json");
for (const entry of entries) {
  // An entry like `lib/index.js` is covered by a directory whitelist entry
  // (`lib`) — the build fills that directory. Accept either exact match or an
  // ancestor directory present in `files`.
  const covered = shipped.has(entry) || entry.split("/").some((_, i, parts) => shipped.has(parts.slice(0, i + 1).join("/")));
  check(`entry ${entry} is in files`, covered, covered ? "" : "entry missing from files");
}

/**
 * Static relative imports of one module: `from "./x.ts"`, `import "./x.ts"`,
 * `import("./x.ts")`, and factory-form `require("./x.ts")`. Bare specifiers
 * (react, peer packages) and `node:` builtins are ignored: those are the
 * runtime's / packer's problem, not the tarball's.
 * @param {string} source - the module's text.
 * @returns {string[]} the imported paths, without the `./` prefix.
 */
function staticImports(source) {
  const found = [];
  const pattern = /(?:from\s*|import\s*\(?\s*|require\s*\(\s*)["'](\.\/[^"']+)["']/g;
  for (const match of source.matchAll(pattern)) {
    found.push(match[1].replace(/^\.\//, ""));
  }
  return found;
}

// --- 2. every SOURCE module reachable from the entry source is under src/host
// The single publishable host bundle is `lib/index.js`, built from
// `src/host/index.ts`. Walking the source graph proves the bundle is a closed
// set over the project's own files (no stray absolute, no leaked peer).
const SRC_ENTRY = join(root, "src", "host", "index.ts");
const seen = new Set();
const queue = [SRC_ENTRY];
while (queue.length > 0) {
  const file = queue.shift();
  if (seen.has(file)) continue;
  seen.add(file);
  const source = readFileSync(file, "utf8");
  for (const dep of staticImports(source)) {
    const abs = join(dirname(file), dep);
    if (!seen.has(abs)) queue.push(abs);
  }
}
check("the host source graph is walkable", seen.size > 0, `${seen.size} module(s) reached`);
// Every reachable source must live under src/host (the build's input root),
// with ONE declared exception: `src/shared/`. That directory is the wire
// contract both halves read (`src/shared/wire.ts`) — TYPE-ONLY exports, erased
// by tsdown at build time, so they add no runtime code to either bundle. Keep
// it that way: a runtime export there would be the first host logic to enter
// the browser artifact, and it would loosen the isolation that
// `docs/ARCHITECTURE.md` §5 assumes.
const SHARED_ROOT = join(root, "src", "shared");
let outside = 0;
for (const file of seen) {
  const inHost = file.startsWith(join(root, "src", "host"));
  const inShared = file.startsWith(SHARED_ROOT);
  if (!inHost && !inShared) outside += 1;
}
check("every host source reachable from the entry lives under src/host (shared type root excepted)",
  outside === 0, outside === 0 ? "" : `${outside} source(s) escaped src/host`);
// The full graph is published as the `lib` directory (one bundle), so the
// whitelist must contain it.
check("files whitelists the built lib/ output", hasLib, hasLib ? "" : "lib missing from files — the host bundle would ship nothing");

// --- 3. every non-directory shipped entry exists (BUILD OUTPUTS SKIP) -------
// `lib` is a directory produced by `npm run build`; `client.js` is the client
// artifact. On a clean checkout without a build they are absent — that is not
// a regression, it is the workbuddy layout, so those two SKIP loudly instead of
// failing. Every other shipped entry (cordis.patch.yml, docs, README...) must
// exist on disk.
for (const entry of shipped) {
  if (entry === "lib" || entry === "client.js") continue;
  if (!entry.endsWith(".js") && !entry.includes(".")) continue; // skip dir-like
  let present = true;
  try { readFileSync(join(root, entry)); } catch { present = false; }
  check(`shipped ${entry} exists`, present, present ? "" : "listed but absent on disk");
}
if (!existsSync(join(root, "client.js"))) {
  console.log("[package.test] SKIP — client.js artifact absent; run `npm run build` to emit it.");
}
if (!existsSync(join(root, "lib", "index.js"))) {
  console.log("[package.test] SKIP — lib/index.js absent; run `npm run build` to emit it.");
}

// --- 4. no hand-written .js source lives at the package root ----------------
// Root must hold only config/docs/asset files; all .js/.ts source lives under
// src/. A stray root .js would be dead weight (or a forgotten artifact).
const rootJs = readdirSync(root).filter((name) => name.endsWith(".js"));
// client.js is the only legitimate root .js and it is a BUILD OUTPUT (git-ignored).
const stray = rootJs.filter((name) => name !== "client.js");
check("no hand-written .js source sits at the package root", stray.length === 0,
  stray.length === 0 ? "" : `stray root .js: ${stray.join(", ")}`);

// --- 5. the browser bundle resolves packages, never paths ------------------
// The Client module table's synchronous `require` (dsh-client-modules,
// `makeRequire`) looks specifiers up by seed word and registered FACTORY ID;
// only `require.async` accepts a `./` path, and only for build-time chunks.
// An unbuilt bundle that requires a relative path therefore loads fine under
// Node in tests — where `import` resolves paths — and throws "missed the
// module table" in the browser: a split that is green everywhere except the
// thing it ships to. This pins the bundle to package specifiers only.
//
// The artifact (client.js) is the authoritative check; when it has not been
// built, fall back to the source (src/client/index.ts), where every relative
// import is bundler-resolved and no runtime `require("./…")` may appear.
{
  const artifact = join(root, "client.js");
  const source = join(root, "src", "client", "index.ts");
  let text = null;
  let label = "";
  if (existsSync(artifact)) { text = readFileSync(artifact, "utf8"); label = "client.js artifact"; }
  else if (existsSync(source)) { text = readFileSync(source, "utf8"); label = "src/client/index.ts source"; }
  if (text === null) {
    console.log("[package.test] SKIP — no client bundle or source to scan for relative requires.");
  } else {
    const scanned = text
      .split("\n")
      .filter((line) => !/^\s*(\/\/|\*)/.test(line))
      .join("\n");
    const relatives = [...scanned.matchAll(/require\s*\(\s*["'](\.\/[^"']+)["']/g)].map((match) => match[1]);
    check(`the client module requires no relative path (${label})`, relatives.length === 0, relatives.join(", "));
    const required = [...new Set([...scanned.matchAll(/require\s*\(\s*["']([^"']+)["']/g)].map((match) => match[1]))];
    check("the client module requires only the platform's package seeds",
      required.every((spec) => spec === "react"), required.join(", "));
  }
}

// --- 6. the test-gate roster is one fact, not three mirrors ----------------
// A suite that exists on disk but is wired into no gate runs for nobody; a
// suite in the roster but not in the CI offline job is a local-only gate; a CI
// line naming a removed file rots silently. All three happened or were one
// refactor away. `retry.test.mjs` and `draw.test.mjs` (89 peer-free checks
// over the shipped 429 self-heal and draw-absorption code) sat in the first
// bucket until this pin.
//
// The roster moved INTO `test/suites.mjs` (2026-10-05) and BOTH entry points
// now invoke it: `npm test` runs `node test/run-all.mjs`, and the CI offline
// job runs that same runner with `--skip=e2e-gate`. This pin used to scrape
// two hand-copied TEXT mirrors with a regex and compare them — which made the
// duplication itself the thing under maintenance, and made the "three-way"
// agreement a fourth place to forget. Now the agreement is structural: CI can
// only agree by invoking the runner that reads the roster.
//
// The one deliberate exception is the network tier: `live-jwks.test.mjs` is
// NOT a default-run check (a green offline run must not reach the platform),
// so it is exempted here and pinned EXCLUDED by its own header.
{
  const TEST_DIR = join(root, "test");
  const EXEMPT = new Set(["live-jwks.test.mjs"]);

  const disk = readdirSync(TEST_DIR)
    .filter((name) => name.endsWith(".test.mjs"))
    .filter((name) => !EXEMPT.has(name));

  // The roster, read as DATA. Both gates execute this same array, so "is the
  // roster complete" is one comparison instead of two scraped string lists
  // that could each swallow a suite of their own.
  const roster = SUITES.map((entry) => entry.name);
  const rosterSet = new Set(roster);
  const ciText = readFileSync(join(root, ".github", "workflows", "ci.yml"), "utf8");

  // disk ⊆ roster: no orphaned suite — the direction that has actually bitten
  // (a suite written and green, running in nobody's gate).
  for (const name of disk) {
    check(`${name} is in the gate roster`, rosterSet.has(name),
      rosterSet.has(name) ? "" : "exists on disk but no gate runs it");
  }
  // roster ⊆ disk: no ghost entry — and unlike the old `*.test.mjs` scrape,
  // this direction now SEES the four gate files, which that regex could not
  // see at all (they are `.mjs`, not `.test.mjs`).
  for (const name of roster) {
    check(`roster entry ${name} exists on disk`, existsSync(join(TEST_DIR, name)),
      "the roster names a file that is not in test/");
  }

  // Both entry points must invoke the RUNNER. A `node test/x.test.mjs` line
  // surviving anywhere in ci.yml means someone pasted a suite list back into
  // the workflow — reintroducing exactly the chain this replaced — so that is
  // pinned as a FAILURE, not merely as drift.
  check("npm test invokes the shared runner", /node test\/run-all\.mjs/.test(manifest.scripts.test ?? ""),
    manifest.scripts.test ?? "");
  check("the CI offline job invokes the same runner", /node test\/run-all\.mjs/.test(ciText),
    ciText.includes("node test/") ? "ci.yml names suites directly; call the runner instead" : "");
  check("ci.yml has no hand-copied suite chain left",
    !/node test\/[\w.-]+\.test\.mjs/.test(ciText),
    "ci.yml still names individual suites; it must call test/run-all.mjs");
  // CI's flags are pinned against the constant, so the two cannot drift by
  // hand: the end-to-end tier is a separate job there (it needs a Host runtime
  // and a build of the shipped artifacts), and everything else is identical.
  check("the CI job's skip flag matches suites.mjs's CI_FLAGS",
    ciText.includes(`test/run-all.mjs ${CI_FLAGS}`),
    `expected \`node test/run-all.mjs ${CI_FLAGS}\` in ci.yml`);

  // The exempted network suite must STAY out of the default gate — if someone
  // wires it in, the pin fails rather than letting a green run reach the platform.
  check("live-jwks.test.mjs stays out of the default gate", !rosterSet.has("live-jwks.test.mjs"),
    "the network tier must not be a default-run check");
}

console.log(JSON.stringify(results, null, 2));
const failed = results.filter((r) => !r.pass);
if (failed.length > 0) {
  console.error(`\n${failed.length}/${results.length} check(s) FAILED`);
  process.exit(1);
}
console.log(`\nall ${results.length} checks passed`);
